#######################
# Étape de build
#######################
FROM python:3.11-slim@sha256:9c85d1d49df54abca1c5db3b4016400e198e9e9bb699f32f1ef8e5c0c2149ccf AS builder

WORKDIR /app
COPY requirements.txt .

# Installer dans /root/.local pour une copie ciblée
RUN pip install --user --no-cache-dir --verbose -r requirements.txt

#######################
# Étape finale
#######################
FROM python:3.11-slim@sha256:9c85d1d49df54abca1c5db3b4016400e198e9e9bb699f32f1ef8e5c0c2149ccf

ENV PATH="/root/.local/bin:${PATH}"
WORKDIR /app

# Copier les dépendances depuis l'étape builder
COPY --from=builder /root/.local /root/.local

# Copier le code source de l'app
COPY . .

# Créer un utilisateur non-root
RUN useradd -m appuser && chown -R appuser /app

USER appuser

EXPOSE 5000

CMD ["python", "app.py"]
