all:
  hosts:
    webserver:
      ansible_host: 192.168.74.131  # L’adresse de mon ordinateur
      ansible_user: ubuntu  # Le nom d’utilisateur
      ansible_ssh_private_key_file: ../todo-app-key  # Ma clé pour ouvrir la porte
